### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by tdooner** [openoakland/opendisclosure#188]
Our site should be legible on mobile screens. Maybe not perfect, but at least legible.

I brought in a library we wrote at Causes for this, called scss-enhance, which allows you to write CSS like

``` scss
p {
  font-size: 14px;

  @include(desktop) {
    font-size: 16px;
  }
}
```

...which will do pretty much what you expect.

Also, bootstrap has some nice stuff (Grid sizings) to help with this too.
